const fs = require("fs");
const { flattenLines } = require("../src/services/invoiceOcr/layout");
const { buildWords, wordsInRegion } = require("../src/services/invoiceOcr/words");
const { claimSupplierFields } = require("../src/services/invoiceOcr/ownership");
const identity = require("../src/services/invoiceOcr/companyIdentity");
const { parseInvoice } = require("../src/services/invoiceOcr/parser");
const a = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
const lines = flattenLines(a.pages);
const parsed = parseInvoice({ pages: a.pages, identity: identity.fromRequest({ name: "BLUECHIP COMPUTER SYSTEM", gstin: "27AABCU9603R1ZM" }) });
const words = wordsInRegion(buildWords(lines), parsed.geometry.supplier);
const r = claimSupplierFields(words);
console.log("PARTY   ", r.partyName);
console.log("ADDRESS ", r.address);
console.log("CITY    ", r.city);
console.log("STATE   ", r.state, "| raw", r.stateRaw);
console.log("PINCODE ", r.pincode);
console.log("PHONE   ", r.phone, "| raw", r.phoneRaw);
console.log("GSTIN   ", r.gstin);
console.log("EMAIL   ", r.email);
console.log("");
console.log("CLAIM MAP");
for (const c of r.claimMap) console.log(`  ${String(c.text).slice(0, 34).padEnd(34)} -> ${c.owner}`);
const banned = ["9601740014","8487961404","GSTIN","2dFOZPPSBESL1ZP","Gujaral","Gujarat","E-Mail","@gmail.com","Stale"];
const leaks = banned.filter((b) => r.address.includes(b));
console.log("");
console.log("ADDRESS LEAKS:", leaks.length ? leaks.join(", ") : "none");
